<a href="https://colab.research.google.com/github/leandroguarato/data_science/blob/master/Analisando_a_Viol%C3%AAncia_no_Rio_de_Janeiro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img alt="Colaboratory logo" width="15%" src="https://raw.githubusercontent.com/carlosfab/escola-data-science/master/img/novo_logo_bg_claro.png">

#### **Data Science na Prática 2.0**
*by [sigmoidal.ai](https://sigmoidal.ai)*

---

**Instruções para o Projeto**

* Você deve importar o pandas e importar a base de dados da Polícia Militar do Rio de Janeiro sobre a violência
  * O arquivo `csv` se encontra no endereço abaixo:
    * https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/violencia_rio.csv
  * Este arquivo `csv` foi pré-processado minimamente por mim, para focar nos pontos aprendidos neste Módulo
  * Este é o site oficial, do Governo do Estado do Rio de Janeiro:
    * http://www.ispdados.rj.gov.br/estatistica.html
  * Um *dashboard* interativo e visual pode ser encontrado no site abaixo:
    * http://www.ispvisualizacao.rj.gov.br/index.html
  * Você está livre para apagar, alterar e acrescentar o que quiser!
  * Se você sentiu dificuldade, não se preocupe! Disponibilizei a minha própria solução para servir de guia, porém tente fazer a sua por você mesmo inicialmente.
    * Se sentir perdido é normal, mas acredite: O seu cérebro vai começar a adquirir uma capacidade nova de pensar em hipóteses e questionar dados.
  
  
---

# Analisando a Violência no Rio de Janeiro

Escreva uma breve introdução contextualizando o problema e o que você vai fazer...

## Obtenção dos Dados


Descreva a fonte dos seus dados e um breve resumo sobre o que se pode esperar desse *dataset*

### Importando os dados

Importe os dados, usando `df = pd.read_csv("endereço_do_csv")`

In [ ]:
# Importando as bibliotecas e o dataset

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/carlosfab/dsnp2/master/datasets/violencia_rio.csv')

## Análise Inicial dos Dados

Breve contextualização...

Descreva e execute as seguintes etapas:

* Qual o tamanho do seu DataFrame (`shape`)
* Extrair e imprimir os nomes das colunas (`columns`)
* Quais os tipos das variáveis (`dtypes`)
* Visualizar as 5 primeiras linhas (`head`)
* Identifique a porcentagem de valores ausentes das colunas

Vejamos o tamanho do *dataset* a ser analisado.

In [ ]:
print('Variáveis/colunas = ', df.shape[1])
print('Número de registros = ', df.shape[0])

Variáveis/colunas =  56
Número de registros =  344

Quais são essas 56 colunas identificadas no *dataset*?

In [ ]:
df.columns

Index(['vano', 'mes', 'hom_doloso', 'lesao_corp_morte', 'latrocinio',
       'hom_por_interv_policial', 'tentat_hom', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_comercio',
       'roubo_residencia', 'roubo_veiculo', 'roubo_carga', 'roubo_transeunte',
       'roubo_em_coletivo', 'roubo_banco', 'roubo_cx_eletronico',
       'roubo_celular', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'indicador_letalidade', 'indicador_roubo_rua', 'indicador_roubo_veic',
       'registro_ocorrencias', 'fase'],
      dtype='object')

Identificadas as colunas, veremos agora a sua estrutura:

In [ ]:
df.dtypes

vano                            int64
mes                             int64
hom_doloso                      int64
lesao_corp_morte              float64
latrocinio                      int64
hom_por_interv_policial       float64
tentat_hom                      int64
lesao_corp_dolosa               int64
estupro                       float64
hom_culposo                   float64
lesao_corp_culposa            float64
roubo_comercio                  int64
roubo_residencia                int64
roubo_veiculo                   int64
roubo_carga                     int64
roubo_transeunte                int64
roubo_em_coletivo               int64
roubo_banco                     int64
roubo_cx_eletronico           float64
roubo_celular                 float64
roubo_conducao_saque          float64
roubo_apos_saque              float64
roubo_bicicleta               float64
outros_roubos                   int64
total_roubos                    int64
furto_veiculos                  int64
furto_transeunte                int64
furto_coletivo                float64
furto_celular                 float64
furto_bicicleta               float64
outros_furtos                   int64
total_furtos                    int64
sequestro                     float64
extorsao                      float64
sequestro_relampago           float64
estelionato                   float64
apreensao_drogas                int64
posse_drogas                  float64
trafico_drogas                float64
apreensao_drogas_sem_autor    float64
recuperacao_veiculos            int64
apf                           float64
aaapai                        float64
cmp                           float64
cmba                          float64
ameaca                        float64
pessoas_desaparecidas         float64
encontro_cadaver                int64
encontro_ossada               float64
pol_militares_mortos_serv     float64
pol_civis_mortos_serv         float64
indicador_letalidade            int64
indicador_roubo_rua             int64
indicador_roubo_veic            int64
registro_ocorrencias          float64
fase                            int64
dtype: object

A partir da visualização da estrutura do *dataset*, veremos agora as suas primeiras linhas:

In [ ]:
df.head()

   vano  mes  hom_doloso  ...  indicador_roubo_veic  registro_ocorrencias  fase
0  1991    1         657  ...                  1174                   NaN     3
1  1991    2         732  ...                  1097                   NaN     3
2  1991    3         713  ...                  1265                   NaN     3
3  1991    4         634  ...                  1415                   NaN     3
4  1991    5         650  ...                  1449                   NaN     3

[5 rows x 56 columns]

Precisamos, então, começar a visualizar e entender o conteúdo do *dataset* mas não sem antes verificar se há registros com informações faltantes:

In [ ]:
(df.isnull().sum() / df.shape[0]).sort_values(ascending=False)

roubo_bicicleta               0.802326
furto_bicicleta               0.802326
apreensao_drogas_sem_autor    0.523256
posse_drogas                  0.523256
apf                           0.523256
aaapai                        0.523256
cmp                           0.523256
trafico_drogas                0.523256
cmba                          0.523256
sequestro_relampago           0.418605
furto_coletivo                0.418605
extorsao                      0.418605
furto_celular                 0.418605
roubo_apos_saque              0.418605
roubo_conducao_saque          0.418605
roubo_cx_eletronico           0.418605
estupro                       0.418605
estelionato                   0.418605
pol_civis_mortos_serv         0.418605
pol_militares_mortos_serv     0.418605
pessoas_desaparecidas         0.383721
encontro_ossada               0.383721
roubo_celular                 0.313953
lesao_corp_culposa            0.279070
ameaca                        0.279070
sequestro                     0.279070
lesao_corp_morte              0.279070
registro_ocorrencias          0.279070
hom_por_interv_policial       0.244186
hom_culposo                   0.244186
tentat_hom                    0.000000
roubo_comercio                0.000000
roubo_residencia              0.000000
latrocinio                    0.000000
lesao_corp_dolosa             0.000000
hom_doloso                    0.000000
roubo_transeunte              0.000000
mes                           0.000000
roubo_veiculo                 0.000000
roubo_carga                   0.000000
fase                          0.000000
roubo_em_coletivo             0.000000
roubo_banco                   0.000000
outros_roubos                 0.000000
total_roubos                  0.000000
furto_veiculos                0.000000
furto_transeunte              0.000000
outros_furtos                 0.000000
total_furtos                  0.000000
apreensao_drogas              0.000000
recuperacao_veiculos          0.000000
encontro_cadaver              0.000000
indicador_letalidade          0.000000
indicador_roubo_rua           0.000000
indicador_roubo_veic          0.000000
vano                          0.000000
dtype: float64

## Informações Estatísticas da Violência no Rio de Janeiro

Breve contextualização...

Descreva e execute as seguintes etapas:

* Imprima o resumo estatístico do seu DataFrame (`describe`)
* Encontre as médias das seguintes variáveis (colunas):
  * `roubo_veiculo`
  * `furto_veiculos`
  * `recuperacao_veiculos`
* Calcule qual a porcentagem de carros recuperados em relação aos carros roubados + carros furtados:
  * $\frac{\text{recuperacao_veiculos}}{\text{roubo_veiculo} + \text{furto_veiculos}}$
* Encontre os valores máximos (`max`) e mínimos (`min`) da coluna `hom_doloso`

In [ ]:
df.describe()

              vano         mes  ...  registro_ocorrencias        fase
count   344.000000  344.000000  ...            248.000000  344.000000
mean   2004.837209    6.453488  ...          53794.161290    2.994186
std       8.289036    3.447759  ...          11039.051992    0.076138
min    1991.000000    1.000000  ...          30621.000000    2.000000
25%    1998.000000    3.000000  ...          45374.500000    3.000000
50%    2005.000000    6.000000  ...          54926.500000    3.000000
75%    2012.000000    9.000000  ...          63292.500000    3.000000
max    2019.000000   12.000000  ...          75403.000000    3.000000

[8 rows x 56 columns]

In [ ]:
media_roubo = df.roubo_veiculo.mean()
media_furto = df.furto_veiculos.mean()
media_recuperacao = df.recuperacao_veiculos.mean()
print('Média de roubo de veículos: ', media_roubo)
print('Média de furto de veículos: ', media_furto)
print('Média de recuperação de veículos: ', media_recuperacao)

Média de roubo de veículos:  2448.6976744186045
Média de furto de veículos:  1674.671511627907
Média de recuperação de veículos:  1772.2383720930231

A partir das médias extraídas anteriormente, podemos inferir o percentual de veículos recuperados em relação ao total daqueles subtraídos de seus proprietários.

In [ ]:
total = media_roubo + media_furto
print(round(media_recuperacao/total,2))

0.43

## Visualização de Dados

Breve contextualização...

Plote e comente os seguintes gráficos:

* Histograma de `hom_doloso`
* Gráfico de linhas para a variável `roubo_em_coletivo`

## Conclusão

Escreva suas conclusões e análises sobre os indicadores de violência do Rio de Janeiro...